permissions:
  contents: write # 打开写入权限

name: Qt

on:
  push: # 推送时触发工作流
    branches: [ "main" ]

# 具体任务
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    # 设置 Qt 环境
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2' # 指定 Qt 版本
        host: 'windows'   # 主机系统
        target: 'desktop' # 目标平台
        arch: 'win64_msvc2019_64' # 架构和编译器
        dir: 'C:\Qt'     # 安装目录

    # 缓存 Qt 安装，这样在下一次运行时可以节省时间
    - name: Cache Qt
      uses: actions/cache@v2
      with:
        path: C:\Qt
        key: ${{ runner.os }}-QtCache-5.15.2

    # 其他构建步骤，比如生成构建文件、编译、测试等
    - name: Configure
      run: |
        mkdir build
        cd build
        # 用于生成构建系统的命令，可能是 qmake 或 cmake
        # 例如：qmake ../your_project.pro -spec win32-msvc

    - name: Build
      run: |
        cd build
        # 用于构建项目的命令，比如 make 或 nmake 或 jom
        # 例如：nmake 或者 jom

    - name: Test
      run: |
        cd build
        # 执行测试
        # 例如：ctest

    # 你可以添加更多的步骤来打包你的应用，上传构建产物到发布页面等等。